name: Java CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installation de l'environnement Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Exécution des tests (Exercice 10.1)
      - name: Clean & test
        run: mvn clean test

      # 4. Génération de l'archive (Exercice 10.2)
      - name: Package project
        run: mvn package -DskipTests # -DskipTests évite de rejouer les tests déjà faits à l'étape précédente

      # 5. Sauvegarde du dossier target (Exercice 10.3)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-build-artifacts
          path: target/