name: Java CI with Maven

on:
  push:
    branches: [ "main" ]  # Déclenchement à chaque push sur main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupération du code source
    - uses: actions/checkout@v4

    # 2. Configuration du JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Phase : Clean & Test (Exercice 10.1)
    - name: Run Tests
      run: mvn clean test

    # 4. Phase : Package (Exercice 10.2)
    - name: Build with Maven (Package)
      run: mvn package -DskipTests # On saute les tests car ils viennent d'être faits

    # 5. Phase : Sauvegarde de l'artefact (Exercice 10.3)
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bank-application-build
        path: target/ # Sauvegarde tout le dossier target